### PR TITLE
simple test to see if pym is already loaded on the page

### PR DESCRIPTION
**Pull request by hobbes7878**

### CODE REVIEW

**Comment by hobbes7878** [comment]
Simple use case for this: I have a service that provides embed codes to users. The embed code includes pym. A user can create multiple embeds for a single page. So that I don't load multiple instances of pym on the parent page, this adds a check to see if it's already defined. 

Welcome to hear better ways to handle this, but this was the simplest I saw.

**Comment by thomaswilburn** [comment]
Thank you for submitting this PR. Because it has merge conflicts, I'm probably going to leave it unmerged at this time, but I think it's a good idea and I'll be adding equivalent code if we do another Pym point release.

**Comment by hobbes7878** [comment]
Thanks, dude. Glad to see you working this repo.

**Comment by zehawki** [comment]
I have the same usecase and I imagine many others would too. I've long been wanting a solution to the restriction that pym has _'Only once per page, no matter how many iframes you will have.'_ The change proposed by @hobbes7878 looks simple and elegant. Why not make this change and release an update? This restriction seems to be the only negative pym has, which otherwise is rather fantastic and just works straight out of the box!

**Pull request closed without merging**
