### PR TITLE
Support setting `title` attribute on Parent iframe

### LINKED ISSUE #101: Support generating iframes with a `title` attribute
[Section 508](http://squizlabs.github.io/HTML_CodeSniffer/Standards/Section508/#prI) and [WCAG 2.0](http://squizlabs.github.io/HTML_CodeSniffer/Standards/WCAG2/2_4_1) both require frames/iframes to have identifying `title` attributes; Pym-generated iframes currently don't.

Suggestions:

1. Let `title` be passed in on the `config` (my preference)
2. Pick up the containing `div`'s `title`

Have a preference? I'm willing to contribute a patch if you'd like.

### PR DESCRIPTION
**Pull request by reefdog**
[Section 508](http://squizlabs.github.io/HTML_CodeSniffer/Standards/Section508/#prI) and [WCAG 2.0](http://squizlabs.github.io/HTML_CodeSniffer/Standards/WCAG2/2_4_1) (accessibility guidelines) require a `title` attribute on iframes. Accept a `title` on the `config` options passed to `pym.Parent` and apply it to the constructed `iframe`.

Fixes #101

### CODE REVIEW

**Comment by eads** [comment]
This all looks good. But if the title is required, shouldn't we set a default title or require it to be set in the settings object rather than making it optional? Might as well encourage good practices!

**Comment by reefdog** [comment]
Making it required to encourage strong accessibility is probably a very good idea. A default, however, would presumably have to be too generic to be meaninful, and thus useless for accessibility, so I'd vote against that. Whatcha think?

**Comment by eads** [comment]
Yeah, I was thinking that too. "Embedded content" or something similar might as well just be "stuff". I guess the question is if that's better than NO title. 

I'd be open to requiring a title, but I'm curious what @coreyhaines @alykat @TylerFisher @hampelm think about this one.

**Comment by alykat** [comment]
Seems fine to me. Two thoughts:

- We'll need to be pretty explicit about the new requirement, update example code, etc.

- We'll need to think about how to integrate this into dailygraphics. Populate it through each graphic's spreadsheet? And probably a generic fallback in case the spreadsheet doesn't exist (rare but could happen).

**Comment by coreyhaines** [comment]
This seems like a good solution. I'm always a bit wary of adding a requirement, but this PR where it is optional, used if provided, seems pretty good. I might pull it over to our fork, as well, just to keep things in parity.

**Comment by eads** [comment]
Cool. I'm going to merge this as-is: it won't be a hard requirement for now, but a best practice.

**Pull request merged**
