### PR TITLE
Add support for persistent player

### PR DESCRIPTION
**Pull request by coreyhaines**
This isn't intended as a request to merge into your codebase, rather to show you what I've done to support the Drupal Ajax Links API that Core Publisher is using now. Over the course of getting it to work on Core Publisher, there were a couple steps.
* I removed the `require.js` support a while ago, as it seemed overkill for this.
* Calling `autoInit()` from within the factory created race conditions if the script was loaded before the appropriate div (or p) was put onto the page. This was resolved by waiting for the `DOMContentLoaded` event and then calling `autoInit()`. As a result, I had to expose `autoInit()` as a function on pym.
* Core Publisher makes use of the Drupal Ajax Links API, which doesn't trigger `DOMContentLoaded` instead triggering a jQuery event called `pi_ajax_links_api_page_loaded`. This is only accessible by setting up a jQuery-based event listener. So, we look for the existence of `pi_ajax_links_api` in the Drupal settings as an indication this event is available.
* Core Publisher has a nasty way of stripping/converting &nbsp; into a blank space, then not showing it on the page. This was the original reason for having to use `<p data-pym-src="...">&nbsp;</p>` instead of a straight `div` tag. However, this has two issues with it:

    1) Pym sometimes seems to convert the `&nbsp;` to a simple space on save, then strip it on display. UGH!
    2) Having a blank space makes it not visible when embedded in a raw page.

  To solve this, I switched to having a placeholder `<p>_</p>` and having pym replace the children with the iframe, rather than using append.

I reverse-engineered the Drupal Ajax Links API from the unminified javascript loaded from a core publisher-based station, but I can't seem to find any good documentation about it. So, there is probably a better way to check for having it turned on. I'm hoping to get NPR DS to chime in on whether there is a better way to detect this.

I've tested this on all of our clients, both with Core Publisher and without, with jQuery and without, and with Persistent Player and without.

Of course, would love any comments/thoughts/etc.

### CODE REVIEW

**Comment by eads** [comment]
Hey @coreyhaines, I'm going to reach out this week. We've let this slip badly and I apologize. I'd like to coordinate though, so we can get it back on track.

**Comment by brentajones** [comment]
Hey folks. I'm leaving this to document the behavior we're seeing on Core Publisher with the Persistent Player turned on, using the Hearken fork of pym.js

We're using [v0.4.11 - 2016-06-07](https://github.com/wearehearken/pym.js/blob/bbcdc330cd5ad05e58f542536e5d604f1445ffa8/dist/pym.js) of the Hearken fork of pym.

* If you land on a page with an embed, the embed loads. if you use page navigation to get to other pages with embeds, they load as well.
    * Example: [Load this page](http://news.stlpublicradio.org/post/can-missouris-vehicle-stops-report-lead-laws-sharper-teeth#stream/0). The pym-embedded table at the bottom of the story will load. Click the byline "Brent Jones" at the top of the page, and click on the second story ("Five things to know about the St. Louis region from the new Census numbers"). The embeds in this story will load.
* If you land on a page without an embed and then use page navigation to get to a page with an embed, the embed will not load. If  you refresh the page, the embed will load.
    * Example: [Load this page](http://news.stlpublicradio.org/people/brent-jones), then click on the first story ("Can Missouri's vehicle stops report lead to laws with sharper teeth?"). The pym-embedded table at the bottom of the story won't load (there will be an underscore). Refresh the page. The table will load.
* If you land on a page without an embed and then use page navigation to get to a page with an embed, the embed will not load. If you use page navigation to get to another page with an embed, it loads.
    * Example: [Load this page](http://news.stlpublicradio.org/people/brent-jones), then click on the first story ("Can Missouri's vehicle stops report lead to laws with sharper teeth?"). The pym-embedded table at the bottom of the story won't load (there will be an underscore). Click the byline "Brent Jones" at the top of the page, and click on the second story ("Five things to know about the St. Louis region from the new Census numbers"). The embeds in this story will load.

**Comment by coreyhaines** [comment]
Hi @eads ! Thanks! Looking forward to chatting. I've been keeping our fork up to date and adding some features for ourselves. I'm getting the feeling that more and more organizations are starting to use our fork. I know that you all have a lot on your plate, and I'm interested in having a chat about potentially taking over maintenance.

**Comment by coreyhaines** [comment]
@brentajones Yeah, I'm talking to NPR DS, and I think we have found the main problem. PP sends their page transition event too early, so the scripts don't have time to load. :( This is a pain, and once I verify it, then we can put in a request to get it changed to send after everything is loaded. I'm hoping to verify it this weekend, the put in the request next week.

**Pull request merged**
