### PR TITLE
added support for all settings as data-attributes for auto-init

### PR DESCRIPTION
**Pull request by AlainVagner**
Fix proposal for issue #130

### CODE REVIEW

**Comment by jjelosua** [comment]
@AlainVagner May I ask why are you treating allowfullscreen as a separate setting instead of moving it into the settings array?

**Comment by AlainVagner** [comment]
@jjelosua IIRC the parameters are of two types, strings and boolean. Only allowfullscreen is a boolean, but the attribute can have the value "true" or "false". If later we will have other boolean parameters, we can have another list of parameters. If you want I can try to refactor this PR to make it a little bit clearer.

**Comment by AlainVagner** [comment]
@jjelosua I have cleaned up my code a bit in my last commit included in this pull request. I manage the different types of data attributes.

**Comment by jjelosua** [comment]
Hi @AlainVagner Looks nice, it seems that the existence of allowfullscreen is enough to enable the full screen mode so we could just test for the existence instead of checking `with === 'true'`. I need to do some testing for some functionality that we may include in pym so we may include your changes in a future 1.1.0. Thanks

**Comment by AlainVagner** [comment]
okay @jjelosua ! Thanks to you.

**Pull request merged**
